### ISSUE TITLE
tsconfig improvements

### ISSUE THREAD

**Issue by Hotell** [ionic-team/stencil-app-starter#15]
there are few redundancies within tsconfig. 

Also I suggest adding `strict:true`

I can send PR if you're ok with that :)

**Comment by jgw96** [comment]
Hey! We would love a PR! Feel free to ping me here when you get it posted and ill review asap. Thanks!

**Comment by jgw96** [comment]
Hey @Hotell , thanks a ton for the PR! We just discussed this internally and for now, we would like to not enable strict mode by default. We think that for beginners, the very strict type checking that strict mode enables will be too much overhead. Whats your thoughts on that?

**Comment by Hotell** [comment]
hey @jgw96 ! yw! 

so I agree and kinda disagree as well :D

- Flow has this enabled by default so no excuses ( also it's easier to adopt because better inference of `any` )
- `tsc --init` has `strict: true` by default so no excuses again :)

writing TS without strict is like writing most of the time without that safety seat belt TS provides for you.

If you don't want to provide strict, at least let's come to a agreement by enabling strictNullChecking

WDYT ?

**Comment by arjunyel** [comment]
@jgw96 @adamdbradley Hi all, thanks for the excellent work on this starter :D I just found this issue after I submitted a pull request for the ionic-pwa-toolkit [turning on strict mode](https://github.com/ionic-team/ionic-pwa-toolkit/pull/17).

I strongly think strict should be on by default. First as @Hotell said Typescript starts projects now with it turned on by default. Second I actually think it helps beginners a ton because it helps them understand where they aren't accounting for things like nulls, some of which a beginner would never expect. As someone who recently was a Typescript beginner, Strict mode helped me catch a ton of bugs that would have been very hard for me to understand if I hit them at run time.

If a user hates it they can opt out but I think Strict is a very safe default. If any work needs to be done to convert the code base I'm happy to do it :) Thanks for your time!

**Comment by jgw96** [comment]
Hello all! In the latest releases of Stencil we have added functionality to allow Stencil to read your tsconfig so you can turn on settings like strict mode optionally. At this time turning on strict mode by default is not something we want to do as it goes against our goal of making things as simple as possible out of the box. Because of this, I am going to close this issue for now. Thanks for using Stencil!
